<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>CVE Feed for Apache -- IoTDB</title>
    <link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/apache/iotdb.rss</link>
    <description>The latest CVEs for Apache -- IoTDB</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Sun, 04 Aug 2024 11:20:13 +0000</lastBuildDate>
    <ttl>60</ttl>
    <item>
      <title>CVE-2020-1952|2024-08-04T06:54:00.401Z -- apache -- iotdb
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2020-1952</link>
      <description>An issue was found in Apache IoTDB .9.0 to 0.9.1 and 0.8.0 to 0.8.2. When starting IoTDB, the JMX port 31999 is exposed with no certification.Then, clients could execute code remotely.</description>
      <guid isPermaLink="false">CVE-2020-1952|2024-08-04T06:54:00.401Z</guid>
      <pubDate>Mon, 27 Apr 2020 16:16:12 +0000</pubDate>
    </item>
  </channel>
</rss>
