<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>CVE Feed for kitabisa -- teler</title>
    <link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/kitabisa/teler.rss</link>
    <description>The latest CVEs for kitabisa -- teler</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Sun, 04 Aug 2024 20:23:04 +0000</lastBuildDate>
    <ttl>60</ttl>
    <item>
      <title>CVE-2020-26213|2024-08-04T15:49:07.177Z -- kitabisa -- teler
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2020-26213</link>
      <description>In teler before version 0.0.1, if you run teler inside a Docker container and encounter `errors.Exit` function, it will cause denial-of-service (`SIGSEGV`) because it doesn't get process ID and process group ID of teler properly to kills. The issue is patched in teler 0.0.1 and 0.0.1-dev5.1.</description>
      <guid isPermaLink="false">CVE-2020-26213|2024-08-04T15:49:07.177Z</guid>
      <pubDate>Fri, 06 Nov 2020 16:45:14 +0000</pubDate>
    </item>
  </channel>
</rss>
