<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>CVE Feed for auth0 -- node-auth0</title>
    <link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/auth0/node-auth0.rss</link>
    <description>The latest CVEs for auth0 -- node-auth0</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Sun, 04 Aug 2024 18:24:43 +0000</lastBuildDate>
    <ttl>60</ttl>
    <item>
      <title>CVE-2020-15125|2024-08-04T13:08:22.304Z -- auth0 -- node-auth0
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2020-15125</link>
      <description>In auth0 (npm package) versions before 2.27.1, a DenyList of specific keys that should be sanitized from the request object contained in the error object is used. The key for Authorization header is not sanitized and in certain cases the Authorization header value can be logged exposing a bearer token. You are affected by this vulnerability if you are using the auth0 npm package, and you are using a Machine to Machine application authorized to use Auth0's management API</description>
      <guid isPermaLink="false">CVE-2020-15125|2024-08-04T13:08:22.304Z</guid>
      <pubDate>Wed, 29 Jul 2020 16:25:15 +0000</pubDate>
    </item>
  </channel>
</rss>
