<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>CVE Feed for fastify -- fastify-websocket</title>
    <link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/fastify/fastify-websocket.rss</link>
    <description>The latest CVEs for fastify -- fastify-websocket</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Sat, 03 Aug 2024 15:23:06 +0000</lastBuildDate>
    <ttl>60</ttl>
    <item>
      <title>CVE-2022-39386|2024-08-03T12:07:41.884Z -- fastify -- fastify-websocket
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2022-39386</link>
      <description>@fastify/websocket provides WebSocket support for Fastify. Any application using @fastify/websocket could crash if a specific, malformed packet is sent. All versions of fastify-websocket are also impacted. That module is deprecated, so it will not be patched. This has been patched in version 7.1.1 (fastify v4) and version 5.0.1 (fastify v3). There are currently no known workarounds. However, it should be possible to attach the error handler manually. The recommended path is upgrading to the patched versions.</description>
      <guid isPermaLink="false">CVE-2022-39386|2024-08-03T12:07:41.884Z</guid>
      <pubDate>Tue, 08 Nov 2022 00:00:00 +0000</pubDate>
    </item>
  </channel>
</rss>
