<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>CVE Feed for oauthlib -- all</title>
    <link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/oauthlib/all.rss</link>
    <description>The latest CVEs for oauthlib -- all products</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Sat, 03 Aug 2024 22:22:22 +0000</lastBuildDate>
    <ttl>60</ttl>
    <item>
      <title>CVE-2022-36087|2024-08-03T09:52:00.509Z -- oauthlib -- oauthlib
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2022-36087</link>
      <description>OAuthLib is an implementation of the OAuth request-signing logic for Python 3.6+. In OAuthLib versions 3.1.1 until 3.2.1, an attacker providing malicious redirect uri can cause denial of service. An attacker can also leverage usage of `uri_validate` functions depending where it is used. OAuthLib applications using OAuth2.0 provider support or use directly `uri_validate` are affected by this issue. Version 3.2.1 contains a patch. There are no known workarounds.</description>
      <guid isPermaLink="false">CVE-2022-36087|2024-08-03T09:52:00.509Z</guid>
      <pubDate>Fri, 09 Sep 2022 00:00:00 +0000</pubDate>
    </item>
  </channel>
</rss>
