<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>CVE Feed for patriksimek -- vm2</title>
    <link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/patriksimek/vm2.rss</link>
    <description>The latest CVEs for patriksimek -- vm2</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Fri, 02 Aug 2024 15:23:05 +0000</lastBuildDate>
    <ttl>60</ttl>
    <item>
      <title>CVE-2023-30547|2024-08-02T14:28:51.599Z -- patriksimek -- vm2
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2023-30547</link>
      <description>vm2 is a sandbox that can run untrusted code with whitelisted Node's built-in modules. There exists a vulnerability in exception sanitization of vm2 for versions up to 3.9.16, allowing attackers to raise an unsanitized host exception inside `handleException()` which can be used to escape the sandbox and run arbitrary code in host context. This vulnerability was patched in the release of version `3.9.17` of `vm2`. There are no known workarounds for this vulnerability. Users are advised to upgrade.</description>
      <guid isPermaLink="false">CVE-2023-30547|2024-08-02T14:28:51.599Z</guid>
      <pubDate>Mon, 17 Apr 2023 21:42:10 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2023-29017|2024-08-02T14:00:14.370Z -- patriksimek -- vm2
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2023-29017</link>
      <description>vm2 is a sandbox that can run untrusted code with whitelisted Node's built-in modules. Prior to version 3.9.15, vm2 was not properly handling host objects passed to `Error.prepareStackTrace` in case of unhandled async errors. A threat actor could bypass the sandbox protections to gain remote code execution rights on the host running the sandbox. This vulnerability was patched in the release of version 3.9.15 of vm2. There are no known workarounds.</description>
      <guid isPermaLink="false">CVE-2023-29017|2024-08-02T14:00:14.370Z</guid>
      <pubDate>Thu, 06 Apr 2023 19:18:34 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2023-29199|2024-08-02T14:00:15.886Z -- patriksimek -- vm2
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2023-29199</link>
      <description>There exists a vulnerability in source code transformer (exception sanitization logic) of vm2 for versions up to 3.9.15, allowing attackers to bypass `handleException()` and leak unsanitized host exceptions which can be used to escape the sandbox and run arbitrary code in host context. A threat actor can bypass the sandbox protections to gain remote code execution rights on the host running the sandbox. This vulnerability was patched in the release of version `3.9.16` of `vm2`.
</description>
      <guid isPermaLink="false">CVE-2023-29199|2024-08-02T14:00:15.886Z</guid>
      <pubDate>Fri, 14 Apr 2023 18:37:03 +0000</pubDate>
    </item>
  </channel>
</rss>
