<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>CVE Feed for snowflake-connector-python -- snowflake-connector-python</title>
    <link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/snowflake-connector-python/snowflake-connector-python.rss</link>
    <description>The latest CVEs for snowflake-connector-python -- snowflake-connector-python</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Sat, 03 Aug 2024 18:24:51 +0000</lastBuildDate>
    <ttl>60</ttl>
    <item>
      <title>CVE-2022-42965|2024-08-03T13:19:05.532Z -- snowflake-connector-python -- snowflake-connector-python
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2022-42965</link>
      <description>An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the snowflake-connector-python PyPI package, when an attacker is able to supply arbitrary input to the undocumented get_file_transfer_type method</description>
      <guid isPermaLink="false">CVE-2022-42965|2024-08-03T13:19:05.532Z</guid>
      <pubDate>Wed, 09 Nov 2022 00:00:00 +0000</pubDate>
    </item>
  </channel>
</rss>
