<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>CVE Feed for ultrajson -- ultrajson</title>
    <link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/ultrajson/ultrajson.rss</link>
    <description>The latest CVEs for ultrajson -- ultrajson</description>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Sat, 03 Aug 2024 18:24:38 +0000</lastBuildDate>
    <ttl>60</ttl>
    <item>
      <title>CVE-2022-31116|2024-08-03T07:11:39.035Z -- ultrajson -- ultrajson
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2022-31116</link>
      <description>UltraJSON is a fast JSON encoder and decoder written in pure C with bindings for Python 3.7+. Affected versions were found to improperly decode certain characters. JSON strings that contain escaped surrogate characters not part of a proper surrogate pair were decoded incorrectly. Besides corrupting strings, this allowed for potential key confusion and value overwriting in dictionaries. All users parsing JSON from untrusted sources are vulnerable. From version 5.4.0, UltraJSON decodes lone surrogates in the same way as the standard library's `json` module does, preserving them in the parsed output. Users are advised to upgrade. There are no known workarounds for this issue.</description>
      <guid isPermaLink="false">CVE-2022-31116|2024-08-03T07:11:39.035Z</guid>
      <pubDate>Tue, 05 Jul 2022 17:35:11 +0000</pubDate>
    </item>
    <item>
      <title>CVE-2022-31117|2024-08-03T07:11:39.016Z -- ultrajson -- ultrajson
</title>
      <link>https://www.cve.org/CVERecord?id=CVE-2022-31117</link>
      <description>UltraJSON is a fast JSON encoder and decoder written in pure C with bindings for Python 3.7+. In versions prior to 5.4.0 an error occurring while reallocating a buffer for string decoding can cause the buffer to get freed twice. Due to how UltraJSON uses the internal decoder, this double free is impossible to trigger from Python. This issue has been resolved in version 5.4.0 and all users should upgrade to UltraJSON 5.4.0. There are no known workarounds for this issue.</description>
      <guid isPermaLink="false">CVE-2022-31117|2024-08-03T07:11:39.016Z</guid>
      <pubDate>Tue, 05 Jul 2022 17:30:13 +0000</pubDate>
    </item>
  </channel>
</rss>
