<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0"><channel><title>CVE Feed for Python Software Foundation -- CPython</title><link>https://raw.githubusercontent.com/deepseas/cvelistV5monitor/main/feeds/python%20software%20foundation/cpython.rss</link><description>The latest CVEs for Python Software Foundation -- CPython</description><docs>http://www.rssboard.org/rss-specification</docs><generator>python-feedgen</generator><lastBuildDate>Fri, 31 May 2024 16:28:20 +0000</lastBuildDate><ttl>60</ttl><item><title>CVE-2024-0450|2024-05-07T21:47:33.040Z -- Python Software Foundation -- CPython
</title><link>https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-0450</link><description>An issue was found in the CPython `zipfile` module affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.

The zipfile module is vulnerable to “quoted-overlap” zip-bombs which exploit the zip format to create a zip-bomb with a high compression ratio. The fixed versions of CPython makes the zipfile module reject zip archives which overlap entries in the archive.

</description><guid isPermaLink="false">CVE-2024-0450|2024-05-07T21:47:33.040Z</guid><pubDate>Tue, 19 Mar 2024 15:12:07 +0000</pubDate></item><item><title>CVE-2024-4030|2024-05-07T21:47:38.876Z -- Python Software Foundation -- CPython
</title><link>https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-4030</link><description>On Windows a directory returned by tempfile.mkdtemp() would not always have permissions set to restrict reading and writing to the temporary directory by other users, instead usually inheriting the correct permissions from the default location. Alternate configurations or users without a profile directory may not have the intended permissions.

If you’re not using Windows or haven’t changed the temporary directory location then you aren’t affected by this vulnerability. On other platforms the returned directory is consistently readable and writable only by the current user.

This issue was caused by Python not supporting Unix permissions on Windows. The fix adds support for Unix “700” for the mkdir function on Windows which is used by mkdtemp() to ensure the newly created directory has the proper permissions.
</description><guid isPermaLink="false">CVE-2024-4030|2024-05-07T21:47:38.876Z</guid><pubDate>Tue, 07 May 2024 21:02:55 +0000</pubDate></item></channel></rss>